defaults: &defaults
  github:
    client_id: <%= ENV["GITHUB_CLIENT_ID"] %>
    client_secret: <%= ENV["GITHUB_CLIENT_SECRET"] %>
    host: <%= ENV["GITHUB_HOST"] || "github.com" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
